#!/bin/bash

echo "calculator"

echo "Enter Two Numbers : "
read a
read b

echo "What would you like to do?"
echo "1 - add"
echo "2 - subtract"
echo "3 - multiply"
echo "4 - divide"
read ch

if [ $ch ==  1 ]
then
        let answer=a+b
        echo $answer
elif [ $ch == 2 ]
then
        let answer=a-b
        echo $answer
elif [ $ch == 3 ]
then
        let answer=a\*b
        echo $answer
elif [ $ch == 4 ]
then
        let answer=a/b
        echo $answer
else
        echo "invalid input"
        exit
fi
